# Generated by Django 4.0.3 on 2022-03-20 09:35

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
                ('phone', models.CharField(max_length=11)),
                ('status', models.CharField(choices=[('Acti', 'Active'), ('Inac', 'Inactive')], default=None, max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('type', models.CharField(choices=[('DOG', 'Cachorro'), ('CAT', 'Gato')], default=None, max_length=3)),
                ('breed', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTI', 'Active'), ('PEND', 'Pending'), ('SOLD', 'Sold')], default=None, max_length=4)),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='petshop.tutor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
